package events

import (
	"encoding/json"
	"errors"
	"strings"
	"time"

	"cyberagent-workbench/internal/idgen"
)

const EnvelopeVersion = "v1"

const (
	RunCreatedEvent                               = "run.created"
	RunModeSelectedEvent                          = "run.mode_selected"
	RunPhaseChangedEvent                          = "run.phase_changed"
	RunExecutionProfileSelectedEvent              = "run.execution_profile_selected"
	RunExecutionInteractionSelectedEvent          = "run.execution_interaction_selected"
	RunExecutionPermissionSelectedEvent           = "run.execution_permission_selected"
	RunBrowserCDPPermissionSelectedEvent          = "run.browser_cdp_permission_selected"
	RunProjectInstructionsRefreshedEvent          = "run.project_instructions_refreshed"
	SessionContinuityNodeCreatedEvent             = "session.continuity_node.created"
	ControlledCommandExecutionPreparedEvent       = "controlled_command.execution_prepared"
	ControlledCommandExecutionCompletedEvent      = "controlled_command.execution_completed"
	HostCommandExecutionPreparedEvent             = "host_command.execution_prepared"
	HostCommandExecutionCompletedEvent            = "host_command.execution_completed"
	DebugTerminalAgentInputGrantedEvent           = "debug_terminal.agent_input_granted"
	DebugTerminalAgentInputPreparedEvent          = "debug_terminal.agent_input_prepared"
	DebugTerminalAgentInputCompletedEvent         = "debug_terminal.agent_input_completed"
	DebugTerminalAgentInputRevokedEvent           = "debug_terminal.agent_input_revoked"
	TerminalSessionStartedEvent                   = "terminal.session_started"
	TerminalSessionStoppedEvent                   = "terminal.session_stopped"
	TerminalAgentInputIssuedEvent                 = "terminal.agent_input_issued"
	TerminalAgentInputRevokedEvent                = "terminal.agent_input_revoked"
	TerminalAgentInputExpiredEvent                = "terminal.agent_input_expired"
	TerminalResizedEvent                          = "terminal.resized"
	TerminalCwdChangedEvent                       = "terminal.cwd_changed"
	TerminalCrashedEvent                          = "terminal.crashed"
	ControlledCommandProposedEvent                = "controlled_command.proposed"
	ControlledCommandProposalReviewedEvent        = "controlled_command.proposal_reviewed"
	ControlledCommandProposalResultRecordedEvent  = "controlled_command.proposal_result_recorded"
	HostCommandProposedEvent                      = "host_command.proposed"
	HostCommandProposalReviewedEvent              = "host_command.proposal_reviewed"
	HostCommandProposalResultRecordedEvent        = "host_command.proposal_result_recorded"
	RunStatusChangedEvent                         = "run.status_changed"
	RunExecutionHandoffRequestedEvent             = "run.execution_handoff_requested"
	RunExecutionHandoffCompletedEvent             = "run.execution_handoff_completed"
	RunWakeScheduledEvent                         = "run.wake_scheduled"
	RunWakeClaimedEvent                           = "run.wake_claimed"
	RunWakeRetriedEvent                           = "run.wake_retried"
	RunWakeExhaustedEvent                         = "run.wake_exhausted"
	RunWakeCancelledEvent                         = "run.wake_cancelled"
	RunWakeHandoffPreparedEvent                   = "run.wake_handoff_prepared"
	RunWakeCompletedEvent                         = "run.wake_completed"
	ScheduledJobCreatedEvent                      = "scheduled_job.created"
	ScheduledJobPausedEvent                       = "scheduled_job.paused"
	ScheduledJobResumedEvent                      = "scheduled_job.resumed"
	ScheduledJobCancelledEvent                    = "scheduled_job.cancelled"
	ScheduledJobClaimedEvent                      = "scheduled_job.claimed"
	ScheduledJobRoundCompletedEvent               = "scheduled_job.round_completed"
	ScheduledJobRoundRetriedEvent                 = "scheduled_job.round_retried"
	ScheduledJobRoundSkippedEvent                 = "scheduled_job.round_skipped"
	ScheduledJobStoppedEvent                      = "scheduled_job.stopped"
	ScheduledJobNotificationEvent                 = "scheduled_job.notification_recorded"
	FileEditApplyRequestedEvent                   = "file_edit.apply_requested"
	FileEditApplyCompletedEvent                   = "file_edit.apply_completed"
	RunExecutionLeaseAcquiredEvent                = "run.execution_lease_acquired"
	RunExecutionLeaseTakenOverEvent               = "run.execution_lease_taken_over"
	RunExecutionLeaseReleasedEvent                = "run.execution_lease_released"
	SessionAttachedEvent                          = "session.attached"
	SessionMessageEvent                           = "session.message_created"
	SessionEvidenceAttachedEvent                  = "session.evidence_attached"
	VerificationEvidenceRecordedEvent             = "verification.evidence_recorded"
	VerificationPlanRecordedEvent                 = "verification.plan_recorded"
	VerificationPlanEvidenceAssociatedEvent       = "verification.plan_evidence_associated"
	VerificationSnapshotReceiptRecordedEvent      = "verification.snapshot_receipt_recorded"
	VerificationSnapshotReviewRecordedEvent       = "verification.snapshot_receipt_review_recorded"
	BrowserLaunchAttemptPreparedEvent             = "browser.launch_attempt_prepared"
	BrowserLaunchLeaseRecordedEvent               = "browser.launch_lease_recorded"
	BrowserLaunchReviewedEvent                    = "browser.launch_reviewed"
	BrowserRuntimeCheckpointRecordedEvent         = "browser.runtime_checkpoint_recorded"
	BrowserRuntimeReceiptRecordedEvent            = "browser.runtime_receipt_recorded"
	AnalyzerStartRequestRegisteredEvent           = "analyzer.start_request_registered"
	AnalyzerStartIntentRecordedEvent              = "analyzer.start_intent_recorded"
	AnalyzerStartLifecycleReceiptRecordedEvent    = "analyzer.start_lifecycle_receipt_recorded"
	AnalyzerExecutionCapabilityIssuedEvent        = "analyzer.execution_capability_issued"
	AnalyzerExecutionCapabilityConsumedEvent      = "analyzer.execution_capability_consumed"
	AnalyzerExecutionCompletedEvent               = "analyzer.execution_completed"
	PolicyDecisionEvent                           = "policy.decision"
	ToolProposedEvent                             = "tool.proposed"
	ToolApprovedEvent                             = "tool.approved"
	ToolDeniedEvent                               = "tool.denied"
	ToolStartedEvent                              = "tool.started"
	ToolCompletedEvent                            = "tool.completed"
	ToolFailedEvent                               = "tool.failed"
	FileEditProposedEvent                         = "file_edit.proposed"
	FileEditApprovedEvent                         = "file_edit.approved"
	FileEditAppliedEvent                          = "file_edit.applied"
	FileEditDeniedEvent                           = "file_edit.denied"
	FileEditFailedEvent                           = "file_edit.failed"
	ApprovalRequestedEvent                        = "approval.requested"
	ApprovalBoundEvent                            = "approval.bound"
	ApprovalDecidedEvent                          = "approval.decided"
	ApprovalGrantCreatedEvent                     = "approval.grant_created"
	ApprovalGrantRevokedEvent                     = "approval.grant_revoked"
	ToolBudgetChargedEvent                        = "tool.budget_charged"
	ToolBudgetExhaustedEvent                      = "tool.budget_exhausted"
	MonetaryBudgetReservedEvent                   = "monetary.budget_reserved"
	MonetaryBudgetSettledEvent                    = "monetary.budget_settled"
	MonetaryBudgetReleasedEvent                   = "monetary.budget_released"
	MonetaryBudgetExhaustedEvent                  = "monetary.budget_exhausted"
	PriceSnapshotImportedEvent                    = "monetary.price_snapshot_imported"
	ChildTaskProposedEvent                        = "agent.child_task_proposed"
	ChildTaskReviewedEvent                        = "agent.child_task_reviewed"
	ChildTaskAdmittedEvent                        = "agent.child_task_admitted"
	DependencyWaitRecordedEvent                   = "dependency.wait_recorded"
	DependencySatisfiedEvent                      = "dependency.satisfied"
	DependencyFailedEvent                         = "dependency.failed"
	DependencyCancelledEvent                      = "dependency.cancelled"
	DependencyExpiredEvent                        = "dependency.expired"
	DependencyDeadlockDetectedEvent               = "dependency.deadlock_detected"
	DependencyLivelockDetectedEvent               = "dependency.livelock_detected"
	ArtifactCreatedEvent                          = "artifact.created"
	LegacyTaskAdaptedEvent                        = "legacy.task_adapted"
	SupervisorCheckpointedEvent                   = "supervisor.checkpointed"
	AgentRegisteredEvent                          = "agent.registered"
	AgentCapacityReservedEvent                    = "agent.capacity_reserved"
	AgentStatusChangedEvent                       = "agent.status_changed"
	AgentMessageSentEvent                         = "agent.message_sent"
	AgentMessageConsumedEvent                     = "agent.message_consumed"
	AgentInboxContextPreparedEvent                = "agent.inbox_context_prepared"
	AgentInboxContextCommittedEvent               = "agent.inbox_context_committed"
	AgentInboxContextSupersededEvent              = "agent.inbox_context_superseded"
	AgentCompletionReportedEvent                  = "agent.completion_reported"
	AgentGraphSnapshottedEvent                    = "agent.graph_snapshotted"
	AgentTurnStartedEvent                         = "agent.turn_started"
	AgentAttemptUsageRecordedEvent                = "agent.usage_recorded"
	AgentTurnCompletedEvent                       = "agent.turn_completed"
	AgentTurnFailedEvent                          = "agent.turn_failed"
	AgentScheduleStartedEvent                     = "agent.schedule_started"
	AgentScheduleStoppedEvent                     = "agent.schedule_stopped"
	AgentOperatorScheduleRequestedEvent           = "agent.operator_schedule_requested"
	AgentDelegationProposedEvent                  = "agent.delegation_proposed"
	AgentDelegationReviewedEvent                  = "agent.delegation_reviewed"
	AgentDelegationApplicationStartedEvent        = "agent.delegation_application_started"
	AgentDelegationAssignmentAdmittedEvent        = "agent.delegation_assignment_admitted"
	AgentDelegationInstructionDeliveredEvent      = "agent.delegation_instruction_delivered"
	AgentDelegationAppliedEvent                   = "agent.delegation_applied"
	AgentDelegationApplicationAbortedEvent        = "agent.delegation_application_aborted"
	PlanDeliveryProposedEvent                     = "plan_delivery.proposed"
	PlanDeliveryDirectionSelectedEvent            = "plan_delivery.direction_selected"
	DeliveryCheckpointRecordedEvent               = "delivery.checkpoint_recorded"
	OperatorSteeringQueuedEvent                   = "operator.steering_queued"
	OperatorSteeringPreparedEvent                 = "operator.steering_prepared"
	OperatorSteeringCommittedEvent                = "operator.steering_committed"
	OperatorSteeringSupersededEvent               = "operator.steering_superseded"
	OperatorSteeringCancelledEvent                = "operator.steering_cancelled"
	OperatorSteeringActionDeferredEvent           = "operator.steering_action_deferred"
	ReadOnlyFanoutPlannedEvent                    = "readonly_fanout.planned"
	ReadOnlyFanoutExecutionStartedEvent           = "readonly_fanout.execution_started"
	ReadOnlyFanoutExecutionRecoveredEvent         = "readonly_fanout.execution_recovered"
	ReadOnlyFanoutShardStartedEvent               = "readonly_fanout.shard_started"
	ReadOnlyFanoutShardCompletedEvent             = "readonly_fanout.shard_completed"
	ReadOnlyFanoutShardFailedEvent                = "readonly_fanout.shard_failed"
	ReadOnlyFanoutShardCancelledEvent             = "readonly_fanout.shard_cancelled"
	ReadOnlyFanoutExecutionCompletedEvent         = "readonly_fanout.execution_completed"
	ReadOnlyFanoutExecutionFailedEvent            = "readonly_fanout.execution_failed"
	ReadOnlyFanoutExecutionCancelledEvent         = "readonly_fanout.execution_cancelled"
	FindingReportGeneratedEvent                   = "report.generated"
	FindingArtifactEvidenceAttachedEvent          = "finding.evidence_attached"
	FindingValidationDecidedEvent                 = "finding.validation_decided"
	FindingAcceptedEvent                          = "finding.accepted"
	FindingRemediationEvidenceAttachedEvent       = "finding.remediation_evidence_attached"
	FindingFixedEvent                             = "finding.fixed"
	SkillSelectionCreatedEvent                    = "skill.selection_created"
	SkillContextPreparedEvent                     = "skill.context_prepared"
	SkillContextCommittedEvent                    = "skill.context_committed"
	SpecialistSkillContextPreparedEvent           = "skill.specialist_context_prepared"
	SpecialistSkillContextCommittedEvent          = "skill.specialist_context_committed"
	ExternalSkillSelectionCreatedEvent            = "skill.external_selection_created"
	ExternalSkillContextPreparedEvent             = "skill.external_context_prepared"
	ExternalSkillContextCommittedEvent            = "skill.external_context_committed"
	ExternalSpecialistSkillContextPreparedEvent   = "skill.external_specialist_context_prepared"
	ExternalSpecialistSkillContextCommittedEvent  = "skill.external_specialist_context_committed"
	SkillCatalogTrustedEvent                      = "skill.catalog_trusted"
	SkillCatalogRevokedEvent                      = "skill.catalog_revoked"
	SkillCatalogPinnedEvent                       = "skill.catalog_pinned"
	SkillCatalogEnabledEvent                      = "skill.catalog_enabled"
	SkillCatalogDisabledEvent                     = "skill.catalog_disabled"
	SkillImportCompletedEvent                     = "skill.import_completed"
	OnceCommandExecutedEvent                      = "once_command.executed"
	GitMutationCompletedEvent                     = "git.mutation_completed"
	GitAdvancedProposedEvent                      = "git.advanced_proposed"
	GitAdvancedStartedEvent                       = "git.advanced_started"
	GitAdvancedCompletedEvent                     = "git.advanced_completed"
	GitAdvancedSequenceUpdatedEvent               = "git.advanced_sequence_updated"
	GitManagedWorktreeUpdatedEvent                = "git.managed_worktree_updated"
	DrydockTrustConfirmedEvent                    = "drydock.trust_confirmed"
	DrydockCreatePreparedEvent                    = "drydock.create_prepared"
	DrydockCreatedEvent                           = "drydock.created"
	DrydockCreateFailedEvent                      = "drydock.create_failed"
	DrydockUseAttestedEvent                       = "drydock.use_attested"
	DrydockCheckpointRecordedEvent                = "drydock.checkpoint_recorded"
	DrydockRewindCompletedEvent                   = "drydock.rewind_completed"
	DrydockUndoCompletedEvent                     = "drydock.undo_completed"
	DrydockForkPreparedEvent                      = "drydock.fork_prepared"
	DrydockDeliveryProposedEvent                  = "drydock.delivery_proposed"
	DrydockCleanupCompletedEvent                  = "drydock.cleanup_completed"
	DrydockRecoveryRequiredEvent                  = "drydock.recovery_required"
	DrydockRecoveredEvent                         = "drydock.recovered"
	GitRemoteCompletedEvent                       = "git.remote_completed"
	WorkspaceCheckpointCreatedEvent               = "workspace.checkpoint_created"
	WorkspaceCheckpointTransactionPreparedEvent   = "workspace.checkpoint_transaction_prepared"
	WorkspaceCheckpointTransactionCompletedEvent  = "workspace.checkpoint_transaction_completed"
	WorkspaceCheckpointTransactionFailedEvent     = "workspace.checkpoint_transaction_failed"
	SandboxManifestPreparedEvent                  = "sandbox.manifest_prepared"
	SandboxManifestValidatedEvent                 = "sandbox.manifest_validated"
	SandboxExecutionCandidateValidatedEvent       = "sandbox.execution_candidate_validated"
	SandboxExecutionPreparedEvent                 = "sandbox.execution_prepared"
	SandboxExecutionLeaseAcquiredEvent            = "sandbox.execution_lease_acquired"
	SandboxExecutionLeaseTakenOverEvent           = "sandbox.execution_lease_taken_over"
	SandboxExecutionLeaseReleasedEvent            = "sandbox.execution_lease_released"
	SandboxExecutionCancelRequestedEvent          = "sandbox.execution_cancel_requested"
	SandboxExecutionCleanupCompletedEvent         = "sandbox.cleanup_completed"
	SandboxPreflightRecordedEvent                 = "sandbox.preflight_recorded"
	SandboxBackendEvidenceRecordedEvent           = "sandbox.backend_evidence_recorded"
	SandboxOutputSimulationRecordedEvent          = "sandbox.output_simulation_recorded"
	SandboxDockerObservationRecordedEvent         = "sandbox.docker_observation_recorded"
	SandboxDockerContainerPlanRecordedEvent       = "sandbox.docker_container_plan_recorded"
	SandboxDockerRehearsalRecordedEvent           = "sandbox.docker_container_rehearsal_recorded"
	SandboxDockerAttemptPreparedEvent             = "sandbox.docker_attempt_prepared"
	SandboxDockerAttemptAcquiredEvent             = "sandbox.docker_attempt_acquired"
	SandboxDockerAttemptTakenOverEvent            = "sandbox.docker_attempt_taken_over"
	SandboxDockerAttemptStagedEvent               = "sandbox.docker_attempt_staged"
	SandboxDockerAttemptCleanupEvent              = "sandbox.docker_attempt_cleanup_confirmed"
	SandboxDockerAttemptFailedEvent               = "sandbox.docker_attempt_failed"
	SandboxDockerAttemptCompletedEvent            = "sandbox.docker_attempt_completed"
	SandboxDockerLifecyclePreparedEvent           = "sandbox.docker_lifecycle_prepared"
	SandboxDockerLifecycleAcquiredEvent           = "sandbox.docker_lifecycle_acquired"
	SandboxDockerLifecycleTakenOverEvent          = "sandbox.docker_lifecycle_taken_over"
	SandboxDockerLifecycleActionPreparedEvent     = "sandbox.docker_lifecycle_action_prepared"
	SandboxDockerLifecycleTransitionEvent         = "sandbox.docker_lifecycle_transition_recorded"
	SandboxDockerLifecycleCompletedEvent          = "sandbox.docker_lifecycle_completed"
	SandboxDockerProductAdmittedEvent             = "sandbox.docker_product_admitted"
	SandboxDockerProductAdmissionDeniedEvent      = "sandbox.docker_product_admission_denied"
	SandboxDockerProductStartRequestedEvent       = "sandbox.docker_product_start_requested"
	SandboxDockerProductLaunchBoundEvent          = "sandbox.docker_product_launch_bound"
	SandboxDockerProductCancelRequestedEvent      = "sandbox.docker_product_cancel_requested"
	SandboxDockerProductCompletedEvent            = "sandbox.docker_product_completed"
	SandboxDockerHostInputRequirementEvent        = "sandbox.docker_host_input_requirement_recorded"
	SandboxDockerHostInputIntentEvent             = "sandbox.docker_host_input_intent_prepared"
	SandboxDockerHostInputStagedEvent             = "sandbox.docker_host_input_staged"
	SandboxDockerHostInputHandoffRequirementEvent = "sandbox.docker_host_input_handoff_requirement_recorded"
	SandboxDockerHostInputHandoffIntentEvent      = "sandbox.docker_host_input_handoff_intent_prepared"
	SandboxDockerHostInputHandoffEvent            = "sandbox.docker_host_input_handoff_completed"
	SandboxDockerRuntimeInputProjectionEvent      = "sandbox.docker_runtime_input_projection_planned"
	AgentProtocolRepairRequestedEvent             = "agent.protocol_repair_requested"
	AgentProtocolRepairStartedEvent               = "agent.protocol_repair_started"
	AgentProtocolRepairCompletedEvent             = "agent.protocol_repair_completed"
	AgentProtocolRepairFailedEvent                = "agent.protocol_repair_failed"
	ModelStartedEvent                             = "model.started"
	ModelCancelRequestedEvent                     = "model.cancel_requested"
	ModelCancelObservedEvent                      = "model.cancel_observed"
	ModelDeltaEvent                               = "model.delta"
	ModelPublicCommentaryEvent                    = "model.public_commentary"
	ModelCompletedEvent                           = "model.completed"
	ModelFailedEvent                              = "model.failed"
	ProtocolRepairRequestedEvent                  = "supervisor.protocol_repair_requested"
	ProtocolRepairStartedEvent                    = "supervisor.protocol_repair_started"
	ProtocolRepairCompletedEvent                  = "supervisor.protocol_repair_completed"
	ProtocolRepairFailedEvent                     = "supervisor.protocol_repair_failed"
	SupervisorToolBatchEvent                      = "supervisor.tool_batch_requested"
	SupervisorToolExecutionStartedEvent           = "supervisor.tool_execution_started"
	SupervisorToolExecutionCompletedEvent         = "supervisor.tool_execution_completed"
	SupervisorToolResultEvent                     = "supervisor.tool_result_recorded"
	SupervisorToolCompleteEvent                   = "supervisor.tool_batch_completed"
	SupervisorActionEvent                         = "supervisor.action_committed"
	SupervisorRunWaitingEvent                     = "supervisor.run_waiting"
	SupervisorRunCompletedEvent                   = "supervisor.run_completed"
	SupervisorRunFailedEvent                      = "supervisor.run_failed"
	SupervisorProgressObservedEvent               = "supervisor.progress_observed"
	SupervisorProgressResetEvent                  = "supervisor.progress_reset"
	SupervisorLivelockDetectedEvent               = "supervisor.livelock_detected"
	WorkItemCreatedEvent                          = "work_item.created"
	WorkItemChangedEvent                          = "work_item.changed"
	NoteCreatedEvent                              = "note.created"
	NoteChangedEvent                              = "note.changed"
)

const (
	SandboxDockerRuntimeInputApplicationPreparedEvent      = "sandbox.docker_runtime_input_application_prepared"
	SandboxDockerRuntimeInputApplicationAcquiredEvent      = "sandbox.docker_runtime_input_application_acquired"
	SandboxDockerRuntimeInputApplicationTakenOverEvent     = "sandbox.docker_runtime_input_application_taken_over"
	SandboxDockerRuntimeInputApplicationFailedEvent        = "sandbox.docker_runtime_input_application_failed"
	SandboxDockerRuntimeInputApplicationCompletedEvent     = "sandbox.docker_runtime_input_application_completed"
	SandboxDockerRuntimeInputResourceInspectedEvent        = "sandbox.docker_runtime_input_resource_inspected"
	SandboxDockerRuntimeInputResourceCleanupPreparedEvent  = "sandbox.docker_runtime_input_resource_cleanup_prepared"
	SandboxDockerRuntimeInputResourceCleanupAcquiredEvent  = "sandbox.docker_runtime_input_resource_cleanup_acquired"
	SandboxDockerRuntimeInputResourceCleanupTakenOverEvent = "sandbox.docker_runtime_input_resource_cleanup_taken_over"
	SandboxDockerRuntimeInputResourceCleanupFailedEvent    = "sandbox.docker_runtime_input_resource_cleanup_failed"
	SandboxDockerRuntimeInputResourceCleanupCompletedEvent = "sandbox.docker_runtime_input_resource_cleanup_completed"
	SandboxDockerStartGateReviewedEvent                    = "sandbox.docker_start_gate_reviewed"
	SandboxDockerProductionEvidenceCapturedEvent           = "sandbox.docker_production_evidence_captured"
	SandboxDockerProductionEvidenceAttemptPreparedEvent    = "sandbox.docker_production_evidence_attempt_prepared"
	SandboxDockerProductionEvidenceAttemptAcquiredEvent    = "sandbox.docker_production_evidence_attempt_acquired"
	SandboxDockerProductionEvidenceAttemptTakenOverEvent   = "sandbox.docker_production_evidence_attempt_taken_over"
	SandboxDockerProductionEvidenceReconciledEvent         = "sandbox.docker_production_evidence_reconciled"
	SandboxDockerProductionEvidenceAttemptFailedEvent      = "sandbox.docker_production_evidence_attempt_failed"
	SandboxDockerProductionEvidenceAttemptCompletedEvent   = "sandbox.docker_production_evidence_attempt_completed"
	SandboxDockerProductionEvidenceHarnessPreparedEvent    = "sandbox.docker_production_evidence_harness_prepared"
	SandboxDockerProductionEvidenceHarnessReconciledEvent  = "sandbox.docker_production_evidence_harness_reconciled"
	SandboxDockerProductionEvidenceHarnessCompletedEvent   = "sandbox.docker_production_evidence_harness_completed"
	SandboxDockerProductionEvidenceReviewedEvent           = "sandbox.docker_production_evidence_reviewed"
	SandboxDockerInputProjectionPreparedEvent              = "sandbox.docker_input_projection_prepared"
	SandboxDockerLogCapturePreparedEvent                   = "sandbox.docker_log_capture_prepared"
	SandboxDockerLogCaptureAcquiredEvent                   = "sandbox.docker_log_capture_acquired"
	SandboxDockerLogCaptureTakenOverEvent                  = "sandbox.docker_log_capture_taken_over"
	SandboxDockerLogCaptureFailedEvent                     = "sandbox.docker_log_capture_failed"
	SandboxDockerLogCaptureCompletedEvent                  = "sandbox.docker_log_capture_completed"
	SandboxDockerOutputStagingPreparedEvent                = "sandbox.docker_output_staging_prepared"
	SandboxDockerOutputStagingAcquiredEvent                = "sandbox.docker_output_staging_acquired"
	SandboxDockerOutputStagingTakenOverEvent               = "sandbox.docker_output_staging_taken_over"
	SandboxDockerOutputStagingFailedEvent                  = "sandbox.docker_output_staging_failed"
	SandboxDockerOutputStagingCompletedEvent               = "sandbox.docker_output_staging_completed"
	SandboxDockerOutputCommitPreparedEvent                 = "sandbox.docker_output_commit_prepared"
	SandboxDockerOutputCommitFailedEvent                   = "sandbox.docker_output_commit_failed"
	SandboxDockerOutputCommitCompletedEvent                = "sandbox.docker_output_commit_completed"
)

type Event struct {
	ID          int64
	EventID     string
	Version     string
	RunID       string
	MissionID   string
	Sequence    int64
	Type        string
	Source      string
	SubjectID   string
	PayloadJSON string
	CreatedAt   time.Time
}

func New(runID string, missionID string, eventType string, source string, subjectID string, payload any) (Event, error) {
	encoded, err := json.Marshal(payload)
	if err != nil {
		return Event{}, err
	}
	event := Event{
		EventID:     idgen.New("evt"),
		Version:     EnvelopeVersion,
		RunID:       strings.TrimSpace(runID),
		MissionID:   strings.TrimSpace(missionID),
		Type:        strings.TrimSpace(eventType),
		Source:      strings.TrimSpace(source),
		SubjectID:   strings.TrimSpace(subjectID),
		PayloadJSON: string(encoded),
		CreatedAt:   time.Now().UTC(),
	}
	return event, event.Validate()
}

func (e Event) Validate() error {
	if strings.TrimSpace(e.EventID) == "" || strings.TrimSpace(e.RunID) == "" || strings.TrimSpace(e.MissionID) == "" {
		return errors.New("event id, run id, and mission id are required")
	}
	if e.Version != EnvelopeVersion {
		return errors.New("unsupported event envelope version")
	}
	if strings.TrimSpace(e.Type) == "" || strings.TrimSpace(e.Source) == "" {
		return errors.New("event type and source are required")
	}
	if !json.Valid([]byte(e.PayloadJSON)) {
		return errors.New("event payload must be valid JSON")
	}
	if e.CreatedAt.IsZero() {
		return errors.New("event timestamp is required")
	}
	return nil
}
