package toolcontract

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"path/filepath"
	"strings"
	"unicode/utf8"
)

type Transport string

const (
	TransportStdio          Transport = "stdio"
	TransportStreamableHTTP Transport = "streamable_http"
)

// CredentialRef contains no secret. A declaration may omit Revision; the host
// must bind the exact current revision before producing a ResolvedLaunch.
type CredentialRef struct {
	ID       string
	Revision string
}

type StdioLaunch struct {
	Command          string
	ExecutableSHA256 string // required only after resolution
	Args             []string
	Env              map[string]string
	Cwd              string
}

type HTTPLaunch struct {
	Endpoint string
	// Headers retains configured, literal values. At actual send, headers
	// generated by HTTP/MCP/authentication MUST take case-insensitive precedence.
	// Coexistence here is valid; it never authorizes overriding SDK session,
	// protocol or host authentication. B owns that transport projection.
	Headers    map[string]string
	Credential *CredentialRef // host-managed bearer binding, not a portable plugin field
}

// LaunchDeclaration preserves version-validated but UNEXPANDED native values.
// A produces it; B alone resolves it using C's trusted LaunchContext. Unsupported
// native fields remain in the source component and require a diagnostic, never
// silent dropping. Empty ProtocolVersions delegates selection to host profiles.
type LaunchDeclaration struct {
	Component        ComponentRef
	Format           string
	FormatVersion    string
	ProtocolVersions []string
	Transport        Transport
	Stdio            *StdioLaunch
	HTTP             *HTTPLaunch
}

type LaunchContext struct {
	InstanceID       string
	InstallRoot      string
	DataRoot         string
	BaseEnv          map[string]string
	ProtocolVersions []string
}

// ResolvedLaunch is a frozen, transient host snapshot. B must not expand it
// again or merge ambient environment at execution. Credentials remain references;
// the transport fetches their secrets only under the bound current revision.
type ResolvedLaunch struct {
	Component        ComponentRef
	InstanceID       string
	Format           string
	FormatVersion    string
	ProtocolVersions []string // permitted negotiation versions, in preference order
	Transport        Transport
	Stdio            *StdioLaunch
	HTTP             *HTTPLaunch
}

func (d LaunchDeclaration) Validate() error {
	if d.Component.Validate() != nil || !normalized(d.Format, 128) ||
		!normalized(d.FormatVersion, 128) || !versions(d.ProtocolVersions, true) {
		return errors.New("launch declaration identity or version is invalid")
	}
	return validateLaunch(d.Transport, d.Stdio, d.HTTP, false)
}

func (h LaunchContext) Validate() error {
	if !normalized(h.InstanceID, 256) || !filepath.IsAbs(h.InstallRoot) ||
		!normalized(h.InstallRoot, 4096) || !filepath.IsAbs(h.DataRoot) ||
		!normalized(h.DataRoot, 4096) || !versions(h.ProtocolVersions, false) ||
		!environment(h.BaseEnv) {
		return errors.New("host launch context is invalid")
	}
	return nil
}

func (r ResolvedLaunch) Validate() error {
	if r.Component.Validate() != nil || !normalized(r.InstanceID, 256) ||
		!normalized(r.Format, 128) || !normalized(r.FormatVersion, 128) ||
		!versions(r.ProtocolVersions, false) {
		return errors.New("resolved launch identity or version is invalid")
	}
	return validateLaunch(r.Transport, r.Stdio, r.HTTP, true)
}

func validateLaunch(kind Transport, stdio *StdioLaunch, remote *HTTPLaunch, resolved bool) error {
	switch kind {
	case TransportStdio:
		if stdio == nil || remote != nil || !normalized(stdio.Command, 4096) ||
			len(stdio.Args) > 256 || !environment(stdio.Env) ||
			(stdio.Cwd != "" && !normalized(stdio.Cwd, 4096)) {
			return errors.New("stdio launch branch is invalid")
		}
		for _, arg := range stdio.Args {
			if !rawText(arg, 65536) {
				return errors.New("stdio argument is invalid")
			}
		}
		if resolved && (!filepath.IsAbs(stdio.Command) || !filepath.IsAbs(stdio.Cwd) ||
			!digest(stdio.ExecutableSHA256)) {
			return errors.New("resolved stdio launch requires absolute paths and executable identity")
		}
	case TransportStreamableHTTP:
		if remote == nil || stdio != nil || !normalized(remote.Endpoint, 8192) ||
			len(remote.Headers) > 128 {
			return errors.New("HTTP launch branch is invalid")
		}
		seen := make(map[string]bool, len(remote.Headers))
		for name, value := range remote.Headers {
			key := http.CanonicalHeaderKey(name)
			if !headerName(name) || seen[key] || !text(value, 65536) {
				return errors.New("HTTP header is invalid or duplicated")
			}
			seen[key] = true
		}
		if c := remote.Credential; c != nil {
			if !normalized(c.ID, 256) || (c.Revision != "" && !normalized(c.Revision, 256)) ||
				(resolved && c.Revision == "") {
				return errors.New("HTTP credential binding is invalid")
			}
		}
		if resolved {
			u, err := url.Parse(remote.Endpoint)
			if err != nil || (u.Scheme != "https" && u.Scheme != "http") ||
				u.Hostname() == "" || u.User != nil || u.Fragment != "" || u.Opaque != "" {
				return errors.New("resolved HTTP endpoint is invalid")
			}
		}
	default:
		return errors.New("launch transport must be explicit")
	}
	return nil
}

func versions(values []string, emptyOK bool) bool {
	if len(values) > 8 || (len(values) == 0 && !emptyOK) {
		return false
	}
	seen := make(map[string]bool, len(values))
	for _, value := range values {
		if !normalized(value, 128) || seen[value] {
			return false
		}
		seen[value] = true
	}
	return true
}

func environment(env map[string]string) bool {
	if len(env) > 1024 {
		return false
	}
	for key, value := range env {
		if !normalized(key, 256) || strings.Contains(key, "=") || !rawText(value, 65536) {
			return false
		}
	}
	return true
}

func rawText(value string, limit int) bool {
	return len(value) <= limit && utf8.ValidString(value) && !strings.ContainsRune(value, 0)
}

func headerName(value string) bool {
	if value == "" || len(value) > 256 {
		return false
	}
	for _, c := range value {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' ||
			strings.ContainsRune("!#$%&'*+-.^_`|~", c)) {
			return false
		}
	}
	return true
}

// FingerprintLaunch uses a private host key rather than publishing a guessable
// hash of low-entropy env/header/query secrets. Do not persist this key with the
// fingerprint. A new key invalidates old fingerprints; it cannot revive grants.
func FingerprintLaunch(hostKey []byte, launch ResolvedLaunch) (string, error) {
	if len(hostKey) < 32 {
		return "", errors.New("launch fingerprint requires a private host key of at least 32 bytes")
	}
	if err := launch.Validate(); err != nil {
		return "", err
	}
	// These local types deliberately omit the anti-serialization methods. JSON
	// sorts map keys and retains argument/version order. Never mutate callers.
	type stdioSnapshot StdioLaunch
	type httpSnapshot HTTPLaunch
	copyValue := struct {
		Component                         ComponentRef
		InstanceID, Format, FormatVersion string
		ProtocolVersions                  []string
		Transport                         Transport
		Stdio                             *stdioSnapshot
		HTTP                              *httpSnapshot
	}{Component: launch.Component, InstanceID: launch.InstanceID,
		Format: launch.Format, FormatVersion: launch.FormatVersion,
		ProtocolVersions: launch.ProtocolVersions, Transport: launch.Transport}
	if launch.Stdio != nil {
		local := stdioSnapshot(*launch.Stdio)
		if local.Args == nil {
			local.Args = []string{}
		}
		if local.Env == nil {
			local.Env = map[string]string{}
		}
		copyValue.Stdio = &local
	}
	if launch.HTTP != nil {
		remote := httpSnapshot(*launch.HTTP)
		remote.Headers = make(map[string]string, len(launch.HTTP.Headers))
		for name, value := range launch.HTTP.Headers {
			remote.Headers[http.CanonicalHeaderKey(name)] = value
		}
		copyValue.HTTP = &remote
	}
	raw, err := json.Marshal(copyValue)
	if err != nil {
		return "", errors.New("could not encode resolved launch")
	}
	mac := hmac.New(sha256.New, hostKey)
	_, _ = mac.Write([]byte("toolcontract.launch.v1\x00"))
	_, _ = mac.Write(raw)
	return hex.EncodeToString(mac.Sum(nil)), nil
}

var errTransientLaunch = errors.New("launch configuration is transient; persist source references and bound fingerprints instead")

func (LaunchDeclaration) MarshalJSON() ([]byte, error) { return nil, errTransientLaunch }
func (ResolvedLaunch) MarshalJSON() ([]byte, error)    { return nil, errTransientLaunch }
func (LaunchContext) MarshalJSON() ([]byte, error)     { return nil, errTransientLaunch }
func (StdioLaunch) MarshalJSON() ([]byte, error)       { return nil, errTransientLaunch }
func (HTTPLaunch) MarshalJSON() ([]byte, error)        { return nil, errTransientLaunch }
func (LaunchDeclaration) String() string               { return "LaunchDeclaration[redacted]" }
func (ResolvedLaunch) String() string                  { return "ResolvedLaunch[redacted]" }
func (LaunchContext) String() string                   { return "LaunchContext[redacted]" }
func (StdioLaunch) String() string                     { return "StdioLaunch[redacted]" }
func (HTTPLaunch) String() string                      { return "HTTPLaunch[redacted]" }
func (d LaunchDeclaration) GoString() string           { return d.String() }
func (r ResolvedLaunch) GoString() string              { return r.String() }
func (h LaunchContext) GoString() string               { return h.String() }
func (s StdioLaunch) GoString() string                 { return s.String() }
func (h HTTPLaunch) GoString() string                  { return h.String() }
