package surfacegovernance

import (
	"bytes"
	"fmt"
	"strings"
)

func Render(registry Registry) ([]byte, error) {
	if err := Validate(registry); err != nil {
		return nil, err
	}

	var output bytes.Buffer
	write := func(format string, args ...any) {
		fmt.Fprintf(&output, format, args...)
	}

	write("<!-- Code generated by `go run ./cmd/surfacecheck -write`; DO NOT EDIT. -->\n\n")
	write("# Surface inventory / 产品 Surface 清单\n\n")
	write("- Registry version: `%s`\n", markdown(registry.Version))
	write("- Machine-readable source: [`surface-registry.json`](surface-registry.json)\n")
	write("- Evidence baseline: `%s`\n", markdown(registry.EvidenceBaseline))
	write("- Authority: [`%s`](../adr/0135-pre-1-0-product-convergence.md)\n", markdown(registry.Authority))
	write("- Reassess by: `%s`\n\n", markdown(registry.ReassessBy))
	write("> %s\n\n", markdown(registry.Governance.AuthorityStatement))

	write("## Classification\n\n")
	write("A Surface is a supported user or control entry point. Backends, capabilities,\n")
	write("providers, packages, and extension seams can carry a support tier without being\n")
	write("counted as another product Surface.\n\n")
	write("| Tier | Product commitment | Allowed changes | New workflow policy | Core release blocker |\n")
	write("| --- | --- | --- | --- | --- |\n")
	for _, tier := range registry.Tiers {
		write("| `%s` | %s | %s | `%s` | %s |\n",
			markdown(tier.ID), markdown(tier.ProductCommitment), markdownList(tier.AllowedChanges),
			markdown(tier.NewWorkflowPolicy), yesNo(tier.CoreReleaseBlocker))
	}

	write("\n## Ownership\n\n")
	write("| Owner ID | Review owner | Responsibilities |\n")
	write("| --- | --- | --- |\n")
	for _, owner := range registry.Owners {
		write("| `%s` | %s | %s |\n", markdown(owner.ID), markdown(owner.Name),
			markdownList(owner.Responsibilities))
	}

	write("\n## Inventory\n\n")
	write("| Item | Kind | Product Surface | Tier | Owner | Current boundary |\n")
	write("| --- | --- | --- | --- | --- | --- |\n")
	for _, entry := range registry.Entries {
		write("| %s | %s | %s | `%s` | `%s` | %s |\n",
			markdown(entry.Name), markdown(entry.Kind), yesNo(entry.CountsAsProductSurface),
			markdown(entry.Tier), markdown(entry.Owner), markdown(entry.Boundary))
	}

	for _, tierID := range requiredTierIDs {
		write("\n## `%s` review records\n\n", markdown(tierID))
		for _, entry := range registry.Entries {
			if entry.Tier != tierID || entry.Lifecycle.Status == "removed" {
				continue
			}
			write("### %s\n\n", markdown(entry.Name))
			write("- **Owner:** `%s`\n", markdown(entry.Owner))
			write("- **Supported platforms:** %s\n", markdownList(entry.SupportedPlatforms))
			write("- **Shared Go Application contract:** %s\n", markdown(entry.ApplicationContract))
			write("- **Authority impact:** %s\n", markdown(entry.AuthorityImpact))
			if entry.Tier == "active" {
				write("- **Release-blocking checks:** %s\n", markdownList(entry.ReleaseBlockingChecks))
			} else {
				write("- **Core release blocker:** No\n")
			}
			write("- **Contract/test checks:** %s\n", markdownList(entry.ContractChecks))
			write("- **Failure/recovery evidence:** %s\n", markdownList(entry.RecoveryEvidence))
			if entry.Tier == "extension-only" {
				write("- **Go-owned controls:** %s\n", markdownList(entry.GoOwnedControls))
			}
			write("- **Compatibility strategy:** %s\n", markdown(entry.CompatibilityStrategy))
			write("- **Deprecation window:** %s\n", markdown(entry.DeprecationWindow))
			write("- **Removal/rollback plan:** %s\n", markdown(entry.RemovalRollbackPlan))
			write("- **Registered by:** %s (initial tier `%s`)\n\n",
				markdown(entry.Lifecycle.RegisteredBy), markdown(entry.Lifecycle.RegisteredTier))
		}
	}

	write("## Entry criteria\n\n")
	write("A new product Surface, a deferred implementation, or a promotion to `active`\n")
	write("must declare every item below in the registry and its bounded decision/PR:\n\n")
	for i, criterion := range registry.Governance.EntryCriteria {
		write("%d. **`%s`:** %s\n", i+1, markdown(criterion.ID), markdown(criterion.Description))
	}

	write("\n## Tier changes and removal\n\n")
	write("- CI compares the proposed registry with the PR base. Existing entries and\n")
	write("  reviewed transition records are append-only, and removed entries stay as\n")
	write("  tombstones. Tier changes are a `lifecycle.transitions` chain. Changing only\n")
	write("  `tier` fails validation. Promotions require an entry review; an\n")
	write("  `active -> maintenance-only` downgrade requires an ADR/decision, release\n")
	write("  notes, a supported replacement, a deprecation notice, and rollback plan.\n")
	write("- Non-emergency removal requires at least **%d days** and **%d tagged\n",
		registry.Governance.DefaultDeprecationDays,
		registry.Governance.MinimumTaggedPrereleases)
	write("  prereleases**, plus export/recovery evidence and old-client/old-store fixtures.\n")
	write("  An emergency shortcut requires a named security advisory and retains the same\n")
	write("  recovery and fixture obligations.\n")
	write("- Maintenance-only work is limited to security, compatibility, data-loss, and\n")
	write("  severe-defect fixes. A new workflow must first append a promotion to `active`.\n")
	write("- Extension-only work is never a core release blocker and cannot bypass the\n")
	write("  Go-owned policy, approval, or Scope controls recorded above.\n")
	write("- %s\n", markdown(registry.Governance.RollbackStatement))

	return output.Bytes(), nil
}

func markdown(value string) string {
	replacer := strings.NewReplacer("|", "\\|", "\r", " ", "\n", " ")
	return strings.TrimSpace(replacer.Replace(value))
}

func markdownList(values []string) string {
	items := make([]string, 0, len(values))
	for _, value := range values {
		items = append(items, "`"+markdown(value)+"`")
	}
	return strings.Join(items, ", ")
}

func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}
