package protocolregistry

import (
	"bytes"
	"fmt"
	"strings"
)

func RenderMarkdown(registry Registry) []byte {
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by go run ./cmd/protocolregistry -write. DO NOT EDIT. -->\n")
	output.WriteString("# Classified protocol registry / 分级协议注册表\n\n")
	output.WriteString("This document is generated from [`protocols/registry.json`](../../protocols/registry.json). ")
	output.WriteString("It describes compatibility governance only: it never grants runtime authority, capabilities, protocol deletion, data migration, or historical checksum changes.\n\n")
	output.WriteString("## Registry summary\n\n")
	output.WriteString("| Family | Class | Owner | Active IDs | Persisted/exported |\n")
	output.WriteString("| --- | --- | --- | ---: | --- |\n")
	for _, family := range registry.Families {
		fmt.Fprintf(&output, "| [%s](#%s) | `%s` | %s | %d | %t |\n",
			escapeTable(family.ID), family.ID, family.Class, escapeTable(family.Owner),
			len(family.ActiveIdentifiers), family.PersistedOrExported)
	}
	output.WriteString("\n## Families\n\n")
	for _, family := range registry.Families {
		fmt.Fprintf(&output, "### %s\n\n", family.ID)
		fmt.Fprintf(&output, "- Class: `%s`\n", family.Class)
		fmt.Fprintf(&output, "- Owner: %s\n", family.Owner)
		fmt.Fprintf(&output, "- Source of truth: %s\n", codeList(family.SourceOfTruth))
		fmt.Fprintf(&output, "- Persistence/export boundary: %s\n", family.PersistenceBoundary)
		fmt.Fprintf(&output, "- Compatibility rule: %s\n", family.CompatibilityRule)
		fmt.Fprintf(&output, "- Retirement gate (`%s`): %s\n", family.RetirementGate.Mode, strings.Join(family.RetirementGate.Requirements, "; "))
		if family.RebuildSource != "" {
			fmt.Fprintf(&output, "- Rebuild source: %s\n", family.RebuildSource)
		}
		if family.RestartPersistenceProof != "" {
			fmt.Fprintf(&output, "- Restart proof: %s\n", family.RestartPersistenceProof)
		}
		output.WriteString("- Writers:\n")
		for _, writer := range family.Writers {
			fmt.Fprintf(&output, "  - `%s` (`%s`, %s) at `%s`\n", writer.ID, versions(writer.Versions), writer.Mode, writer.Source)
		}
		output.WriteString("- Readers:\n")
		for _, reader := range family.Readers {
			fmt.Fprintf(&output, "  - `%s` (`%s`, %s) at `%s`\n", reader.ID, versions(reader.Versions), reader.Status, reader.Source)
		}
		fmt.Fprintf(&output, "\n<details><summary>%d active identifiers</summary>\n\n", len(family.ActiveIdentifiers))
		for _, identifier := range family.ActiveIdentifiers {
			fmt.Fprintf(&output, "- `%s`\n", identifier)
		}
		output.WriteString("\n</details>\n\n")
		if len(family.RetiredIdentifiers) != 0 {
			fmt.Fprintf(&output, "<details><summary>%d retained retirement records</summary>\n\n", len(family.RetiredIdentifiers))
			for _, retired := range family.RetiredIdentifiers {
				fmt.Fprintf(&output, "- `%s`: %s\n", retired.Identifier, retired.Decision)
			}
			output.WriteString("\n</details>\n\n")
		}
	}
	output.WriteString("## Explicit test and golden allowlist\n\n")
	output.WriteString("These identifiers remain inside the scan. Each exemption is bound to exact files; moving or adding an occurrence requires registry review.\n\n")
	output.WriteString("| Identifier | Kind | Exact sources | Reason |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	for _, entry := range registry.TestAndGoldenAllowlist {
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s |\n", entry.Identifier, entry.Kind,
			codeList(entry.Sources), escapeTable(entry.Reason))
	}
	output.WriteString("\n## v1 to v2 compatibility examples\n\n")
	output.WriteString("| Example | Old fixture | Readers | Writer | Unknown version | Retirement check |\n")
	output.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, example := range registry.CompatibilityExamples {
		fmt.Fprintf(&output, "| `%s` | `%s` | `%s` | `v%d` | `%s` | %s |\n",
			example.ID, example.OldFixture, versions(example.ReaderVersions), example.WriterVersion,
			example.UnknownVersionBehavior, escapeTable(example.ReaderRetirementCheck))
	}
	return output.Bytes()
}

func versions(items []int) string {
	values := make([]string, 0, len(items))
	for _, item := range items {
		values = append(values, fmt.Sprintf("v%d", item))
	}
	return strings.Join(values, ", ")
}

func codeList(items []string) string {
	values := make([]string, 0, len(items))
	for _, item := range items {
		values = append(values, "`"+item+"`")
	}
	return strings.Join(values, ", ")
}

func escapeTable(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", "\\|"), "\n", " ")
}
