package browserruntime

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"cyberagent-workbench/internal/outputsafe"
	"cyberagent-workbench/internal/redact"
	"golang.org/x/net/html"
)

const (
	FullCDPPageSnapshotProtocolVersion = "full_cdp_page_snapshot.v1"
	FullCDPInteractionProtocolVersion  = "full_cdp_interaction.v1"
	FullCDPScreenshotProtocolVersion   = "full_cdp_screenshot.v1"
	MaxFullCDPPageSnapshotHTMLBytes    = 1024 * 1024
	MaxFullCDPPageSnapshotTextBytes    = 48 * 1024
	MaxFullCDPPageSnapshotElements     = 256
	MaxFullCDPPageElementTextRunes     = 512
	MaxFullCDPModelInputBytes          = 16 * 1024
	fullCDPSelectorProvenanceTTL       = time.Minute
)

type fullCDPDocumentIdentity struct {
	CanonicalURL string
	FrameID      string
	LoaderID     string
	RootNodeID   int64
	HTMLSHA256   string
}

func (identity fullCDPDocumentIdentity) sameNavigation(other fullCDPDocumentIdentity) bool {
	return identity.CanonicalURL != "" && identity.CanonicalURL == other.CanonicalURL &&
		identity.FrameID != "" && identity.FrameID == other.FrameID &&
		identity.LoaderID != "" && identity.LoaderID == other.LoaderID &&
		identity.RootNodeID > 0 && identity.RootNodeID == other.RootNodeID
}

func (identity fullCDPDocumentIdentity) sameExact(other fullCDPDocumentIdentity) bool {
	return identity.sameNavigation(other) && identity.HTMLSHA256 != "" &&
		identity.HTMLSHA256 == other.HTMLSHA256
}

type fullCDPSelectorProvenance struct {
	BackendNodeID int64
	Tag           string
	Type          string
	Disabled      bool
}

type fullCDPSelectorSnapshot struct {
	Identity  fullCDPDocumentIdentity
	Selectors map[string]fullCDPSelectorProvenance
	IssuedAt  time.Time
	ExpiresAt time.Time
}

type fullCDPElementIdentity struct {
	BackendNodeID int64
	Tag           string
	Type          string
	Disabled      bool
	ReadOnly      bool
	Hidden        bool
}

var (
	fullCDPSimpleID     = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]{0,127}$`)
	fullCDPSelectorPart = regexp.MustCompile(`^[a-z][a-z0-9-]{0,63}:nth-of-type\([1-9][0-9]{0,6}\)$`)
)

// FullCDPPageElement is a bounded, redacted model-facing representation of an
// interactive DOM element. Selector is generated by the runtime and can be
// used only while this remains the most recent stable session snapshot;
// page-provided script is never run.
type FullCDPPageElement struct {
	Selector string `json:"selector"`
	Tag      string `json:"tag"`
	Role     string `json:"role,omitempty"`
	Name     string `json:"name,omitempty"`
	Type     string `json:"type,omitempty"`
	Disabled bool   `json:"disabled"`
}

type FullCDPPageSnapshot struct {
	ProtocolVersion    string               `json:"protocol_version"`
	CanonicalURL       string               `json:"canonical_url"`
	Title              string               `json:"title,omitempty"`
	Text               string               `json:"text,omitempty"`
	Elements           []FullCDPPageElement `json:"elements"`
	AccessibilityNodes int                  `json:"accessibility_nodes"`
	Truncated          bool                 `json:"truncated"`
	UntrustedEvidence  bool                 `json:"untrusted_evidence"`
	CompletedAt        time.Time            `json:"completed_at"`
	Fingerprint        string               `json:"fingerprint"`
}

type FullCDPInteractionResult struct {
	ProtocolVersion string    `json:"protocol_version"`
	CanonicalURL    string    `json:"canonical_url"`
	Action          string    `json:"action"`
	Selector        string    `json:"selector"`
	CompletedAt     time.Time `json:"completed_at"`
	Fingerprint     string    `json:"fingerprint"`
}

// FullCDPScreenshotMetadata deliberately omits PNG bytes. The model receives
// only a bounded integrity/size receipt plus a separately authorized artifact
// locator; callers persist the PNG without placing base64 in normal tool JSON.
type FullCDPScreenshotMetadata struct {
	ProtocolVersion   string    `json:"protocol_version"`
	CanonicalURL      string    `json:"canonical_url"`
	MediaType         string    `json:"media_type"`
	Bytes             int       `json:"bytes"`
	SHA256            string    `json:"sha256"`
	UntrustedEvidence bool      `json:"untrusted_evidence"`
	CompletedAt       time.Time `json:"completed_at"`
	Fingerprint       string    `json:"fingerprint"`
}

type FullCDPScreenshotCapture struct {
	Metadata FullCDPScreenshotMetadata `json:"metadata"`
	PNG      []byte                    `json:"-"`
}

func (client *restrictedCDPClient) captureFullCDPDocument(ctx context.Context,
	includeHTML bool,
) (fullCDPDocumentIdentity, string, error) {
	if client == nil || !client.fullCDP {
		return fullCDPDocumentIdentity{}, "", ErrBrowserRuntimeBoundary
	}
	var frameTree struct {
		FrameTree struct {
			Frame struct {
				ID       string `json:"id"`
				LoaderID string `json:"loaderId"`
				URL      string `json:"url"`
			} `json:"frame"`
		} `json:"frameTree"`
	}
	if err := client.call(ctx, client.sessionID, "Page.getFrameTree",
		map[string]any{}, &frameTree); err != nil {
		return fullCDPDocumentIdentity{}, "", err
	}
	frame := frameTree.FrameTree.Frame
	frameDecision := client.scope.AuthorizeNavigation(frame.URL)
	if !validRestrictedCDPToken(frame.ID) || !validRestrictedCDPToken(frame.LoaderID) ||
		!frameDecision.Allowed {
		return fullCDPDocumentIdentity{}, "", errors.New(
			"full CDP frame identity is outside scope or malformed")
	}
	var document struct {
		Root struct {
			NodeID      int64  `json:"nodeId"`
			NodeName    string `json:"nodeName"`
			DocumentURL string `json:"documentURL"`
		} `json:"root"`
	}
	if err := client.call(ctx, client.sessionID, "DOM.getDocument",
		map[string]any{"depth": 0, "pierce": false}, &document); err != nil {
		return fullCDPDocumentIdentity{}, "", err
	}
	documentDecision := client.scope.AuthorizeNavigation(document.Root.DocumentURL)
	if !documentDecision.Allowed || documentDecision.CanonicalURL != frameDecision.CanonicalURL ||
		document.Root.NodeID <= 0 || !validDOMNodeName(document.Root.NodeName) {
		return fullCDPDocumentIdentity{}, "", errors.New(
			"full CDP document identity changed or is malformed")
	}
	identity := fullCDPDocumentIdentity{CanonicalURL: documentDecision.CanonicalURL,
		FrameID: frame.ID, LoaderID: frame.LoaderID, RootNodeID: document.Root.NodeID}
	if !includeHTML {
		return identity, "", nil
	}
	var outer struct {
		HTML string `json:"outerHTML"`
	}
	if err := client.call(ctx, client.sessionID, "DOM.getOuterHTML",
		map[string]any{"nodeId": document.Root.NodeID}, &outer); err != nil {
		return fullCDPDocumentIdentity{}, "", err
	}
	if outer.HTML == "" || len([]byte(outer.HTML)) > MaxFullCDPPageSnapshotHTMLBytes ||
		!utf8.ValidString(outer.HTML) {
		return fullCDPDocumentIdentity{}, "", errors.New(
			"full CDP DOM snapshot is empty or exceeds its bound")
	}
	digest := sha256.Sum256([]byte(outer.HTML))
	identity.HTMLSHA256 = hex.EncodeToString(digest[:])
	return identity, outer.HTML, nil
}

func (runtime *FullCDPSession) clearFullCDPSelectorSnapshot() {
	if runtime != nil {
		runtime.selectorSnapshot = fullCDPSelectorSnapshot{}
	}
}

func (runtime *FullCDPSession) captureFullCDPSelectorProvenance(ctx context.Context,
	elements []FullCDPPageElement,
) (map[string]fullCDPSelectorProvenance, error) {
	selectors := make(map[string]fullCDPSelectorProvenance, len(elements))
	for _, element := range elements {
		if _, duplicate := selectors[element.Selector]; duplicate {
			return nil, errors.New("full CDP snapshot emitted an ambiguous selector")
		}
		nodeID, found, err := runtime.client.querySelector(ctx, element.Selector)
		if err != nil || !found {
			return nil, errors.Join(err,
				errors.New("full CDP snapshotted selector no longer resolves"))
		}
		described, err := runtime.client.describeFullCDPElement(ctx, nodeID)
		provenance := fullCDPSelectorProvenance{BackendNodeID: described.BackendNodeID,
			Tag: element.Tag, Type: strings.ToLower(element.Type), Disabled: element.Disabled}
		if err != nil || validateFullCDPElement(provenance, described, false) != nil {
			return nil, errors.Join(err,
				errors.New("full CDP snapshotted selector identity drifted"))
		}
		selectors[element.Selector] = provenance
	}
	return selectors, nil
}

func (runtime *FullCDPSession) installFullCDPSelectorSnapshot(
	identity fullCDPDocumentIdentity, selectors map[string]fullCDPSelectorProvenance,
) {
	now := time.Now().UTC()
	runtime.selectorSnapshot = fullCDPSelectorSnapshot{Identity: identity,
		Selectors: selectors, IssuedAt: now, ExpiresAt: now.Add(fullCDPSelectorProvenanceTTL)}
}

func (runtime *FullCDPSession) authorizeFullCDPSelector(
	identity fullCDPDocumentIdentity, selector string, forType bool,
) (fullCDPSelectorProvenance, error) {
	if runtime == nil || !validFullCDPModelSelector(selector) {
		return fullCDPSelectorProvenance{}, ErrBrowserRuntimeBoundary
	}
	snapshot := runtime.selectorSnapshot
	now := time.Now().UTC()
	provenance, present := snapshot.Selectors[selector]
	if !present || snapshot.IssuedAt.IsZero() || snapshot.ExpiresAt.IsZero() ||
		now.Before(snapshot.IssuedAt) || !now.Before(snapshot.ExpiresAt) ||
		!snapshot.Identity.sameExact(identity) || provenance.Disabled ||
		(forType && !fullCDPProvenanceAllowsType(provenance)) {
		runtime.clearFullCDPSelectorSnapshot()
		return fullCDPSelectorProvenance{}, errors.New(
			"full CDP selector is not authorized by the latest stable snapshot")
	}
	return provenance, nil
}

func fullCDPProvenanceAllowsType(value fullCDPSelectorProvenance) bool {
	if value.Disabled {
		return false
	}
	switch value.Tag {
	case "textarea":
		return true
	case "input":
		switch strings.ToLower(value.Type) {
		case "", "text", "search", "email", "url", "tel", "password":
			return true
		}
	}
	return false
}

func (client *restrictedCDPClient) describeFullCDPElement(ctx context.Context,
	nodeID int64,
) (fullCDPElementIdentity, error) {
	if client == nil || !client.fullCDP || nodeID <= 0 {
		return fullCDPElementIdentity{}, ErrBrowserRuntimeBoundary
	}
	var result struct {
		Node struct {
			BackendNodeID int64    `json:"backendNodeId"`
			NodeName      string   `json:"nodeName"`
			Attributes    []string `json:"attributes"`
		} `json:"node"`
	}
	if err := client.call(ctx, client.sessionID, "DOM.describeNode",
		map[string]any{"nodeId": nodeID, "depth": 0, "pierce": false}, &result); err != nil {
		return fullCDPElementIdentity{}, err
	}
	if result.Node.BackendNodeID <= 0 || !validDOMNodeName(result.Node.NodeName) ||
		len(result.Node.Attributes) > 256 || len(result.Node.Attributes)%2 != 0 {
		return fullCDPElementIdentity{}, errors.New(
			"full CDP element identity is malformed")
	}
	attributes := make(map[string]string, len(result.Node.Attributes)/2)
	for index := 0; index < len(result.Node.Attributes); index += 2 {
		name := strings.ToLower(strings.TrimSpace(result.Node.Attributes[index]))
		value := strings.TrimSpace(result.Node.Attributes[index+1])
		if name == "" || len(name) > 128 || len(value) > 4096 || !utf8.ValidString(value) {
			return fullCDPElementIdentity{}, errors.New(
				"full CDP element attributes are malformed")
		}
		attributes[name] = value
	}
	_, disabled := attributes["disabled"]
	_, readOnly := attributes["readonly"]
	_, hidden := attributes["hidden"]
	disabled = disabled || strings.EqualFold(attributes["aria-disabled"], "true")
	hidden = hidden || strings.EqualFold(attributes["aria-hidden"], "true")
	return fullCDPElementIdentity{BackendNodeID: result.Node.BackendNodeID,
		Tag: strings.ToLower(result.Node.NodeName), Type: strings.ToLower(attributes["type"]),
		Disabled: disabled, ReadOnly: readOnly, Hidden: hidden}, nil
}

func validateFullCDPElement(provenance fullCDPSelectorProvenance,
	element fullCDPElementIdentity, forType bool,
) error {
	if element.BackendNodeID <= 0 || provenance.BackendNodeID <= 0 ||
		element.BackendNodeID != provenance.BackendNodeID || element.Tag != provenance.Tag ||
		element.Type != strings.ToLower(provenance.Type) || element.Disabled || element.Hidden ||
		(forType && (element.ReadOnly || !fullCDPProvenanceAllowsType(provenance))) {
		return errors.New("full CDP selector target drifted or is not interactable")
	}
	return nil
}

func (runtime *FullCDPSession) NavigateFullCDP(ctx context.Context,
	rawURL string,
) (RestrictedNavigationResult, error) {
	if runtime == nil || !runtime.authorization.NavigateAuthorized {
		return RestrictedNavigationResult{}, ErrBrowserRuntimeBoundary
	}
	decision := runtime.session.Scope.AuthorizeNavigation(rawURL)
	if !decision.Allowed {
		return RestrictedNavigationResult{}, errors.New(
			"full CDP navigation target is outside the exact loopback origin")
	}
	release, operationContext, cancel, err := runtime.beginOperation(ctx)
	if err != nil {
		return RestrictedNavigationResult{}, err
	}
	defer release()
	defer cancel()
	runtime.clearFullCDPSelectorSnapshot()
	allowedBefore, blockedBefore := runtime.client.allowedRequests,
		runtime.client.blockedRequests
	runtime.client.pageLoaded = false
	runtime.client.blockedDocument = false
	var navigation struct {
		FrameID   string `json:"frameId"`
		ErrorText string `json:"errorText"`
	}
	if err := runtime.client.call(operationContext, runtime.client.sessionID,
		"Page.navigate", map[string]any{"url": decision.CanonicalURL},
		&navigation); err != nil {
		return RestrictedNavigationResult{}, err
	}
	if navigation.ErrorText != "" || runtime.client.blockedDocument {
		return RestrictedNavigationResult{}, errors.New("full CDP navigation was blocked")
	}
	if err := runtime.client.waitForPageLoad(operationContext); err != nil {
		return RestrictedNavigationResult{}, err
	}
	finalURL, _, _, err := runtime.client.documentIdentity(operationContext)
	if err != nil {
		return RestrictedNavigationResult{}, err
	}
	result := RestrictedNavigationResult{
		ProtocolVersion: RestrictedNavigationProtocolVersion,
		Authorization:   runtime.authorization.Fingerprint, CanonicalURL: finalURL,
		AllowedRequests: runtime.client.allowedRequests - allowedBefore,
		BlockedRequests: runtime.client.blockedRequests - blockedBefore,
		ScopeValidated:  true, RedirectsValidated: true, UntrustedEvidence: true,
		CompletedAt: time.Now().UTC(),
	}
	result.Fingerprint = browserRuntimeFingerprint(result)
	return result, nil
}

func (runtime *FullCDPSession) SnapshotFullCDP(ctx context.Context) (
	FullCDPPageSnapshot, error,
) {
	if runtime == nil || !runtime.authorization.DOMMetadataAuthorized {
		return FullCDPPageSnapshot{}, ErrBrowserRuntimeBoundary
	}
	release, operationContext, cancel, err := runtime.beginOperation(ctx)
	if err != nil {
		return FullCDPPageSnapshot{}, err
	}
	defer release()
	defer cancel()
	before, outerHTML, err := runtime.client.captureFullCDPDocument(
		operationContext, true)
	if err != nil {
		return FullCDPPageSnapshot{}, err
	}
	document, err := html.Parse(strings.NewReader(outerHTML))
	if err != nil {
		return FullCDPPageSnapshot{}, errors.New("full CDP DOM snapshot is malformed")
	}
	title, text, elements, truncated := summarizeFullCDPDocument(document)
	var accessibility struct {
		Nodes []struct {
			Ignored bool `json:"ignored"`
		} `json:"nodes"`
	}
	if err := runtime.client.call(operationContext, runtime.client.sessionID,
		"Accessibility.getFullAXTree", map[string]any{"depth": 64},
		&accessibility); err != nil {
		return FullCDPPageSnapshot{}, err
	}
	accessibilityCount := 0
	for _, node := range accessibility.Nodes {
		if !node.Ignored {
			accessibilityCount++
		}
	}
	selectorProvenance, err := runtime.captureFullCDPSelectorProvenance(
		operationContext, elements)
	if err != nil {
		runtime.clearFullCDPSelectorSnapshot()
		return FullCDPPageSnapshot{}, err
	}
	after, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(after) {
		runtime.clearFullCDPSelectorSnapshot()
		if err != nil {
			return FullCDPPageSnapshot{}, err
		}
		return FullCDPPageSnapshot{}, errors.New(
			"full CDP document changed while the snapshot was captured")
	}
	runtime.installFullCDPSelectorSnapshot(before, selectorProvenance)
	result := FullCDPPageSnapshot{ProtocolVersion: FullCDPPageSnapshotProtocolVersion,
		CanonicalURL: before.CanonicalURL, Title: title, Text: text, Elements: elements,
		AccessibilityNodes: accessibilityCount, Truncated: truncated,
		UntrustedEvidence: true, CompletedAt: time.Now().UTC()}
	result.Fingerprint = browserRuntimeFingerprint(result)
	return result, nil
}

func (runtime *FullCDPSession) ClickFullCDP(ctx context.Context,
	selector string,
) (FullCDPInteractionResult, error) {
	if runtime == nil || !runtime.authorization.DOMMetadataAuthorized ||
		!validFullCDPModelSelector(selector) {
		return FullCDPInteractionResult{}, ErrBrowserRuntimeBoundary
	}
	release, operationContext, cancel, err := runtime.beginOperation(ctx)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	defer release()
	defer cancel()
	before, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	provenance, err := runtime.authorizeFullCDPSelector(before, selector, false)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	nodeID, found, err := runtime.client.querySelector(operationContext, selector)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	if !found {
		return FullCDPInteractionResult{}, errors.New("full CDP selector did not match")
	}
	element, err := runtime.client.describeFullCDPElement(operationContext, nodeID)
	if err != nil || validateFullCDPElement(provenance, element, false) != nil {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP click target does not match snapshot provenance"))
	}
	if err := runtime.client.call(operationContext, runtime.client.sessionID,
		"DOM.scrollIntoViewIfNeeded", map[string]any{"nodeId": nodeID},
		&struct{}{}); err != nil {
		return FullCDPInteractionResult{}, err
	}
	rectangle, err := runtime.client.nodeRectangle(operationContext, nodeID)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	stable, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(stable) {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP document changed before click dispatch"))
	}
	stableElement, err := runtime.client.describeFullCDPElement(operationContext, nodeID)
	if err != nil || stableElement.BackendNodeID != element.BackendNodeID ||
		validateFullCDPElement(provenance, stableElement, false) != nil {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP click target changed before dispatch"))
	}
	x := float64(rectangle.Min.X+rectangle.Max.X) / 2
	y := float64(rectangle.Min.Y+rectangle.Max.Y) / 2
	runtime.clearFullCDPSelectorSnapshot()
	runtime.client.pageLoaded = false
	for _, eventType := range []string{"mousePressed", "mouseReleased"} {
		if err := runtime.client.call(operationContext, runtime.client.sessionID,
			"Input.dispatchMouseEvent", map[string]any{"type": eventType, "x": x,
				"y": y, "button": "left", "clickCount": 1}, &struct{}{}); err != nil {
			return FullCDPInteractionResult{}, err
		}
	}
	// A click may start a navigation after Input.dispatchMouseEvent returns.
	// Give the fixed protocol a short settle window, then always re-read the
	// document identity through TargetScope before publishing success. An
	// external redirect remains blocked by Fetch and can never be reported as a
	// successful click destination.
	settleUntil := time.Now().Add(750 * time.Millisecond)
	finalURL := before.CanonicalURL
	for {
		observed, _, identityErr := runtime.client.captureFullCDPDocument(
			operationContext, false)
		if identityErr != nil {
			return FullCDPInteractionResult{}, identityErr
		}
		finalURL = observed.CanonicalURL
		if runtime.client.pageLoaded || !time.Now().Before(settleUntil) {
			break
		}
		timer := time.NewTimer(25 * time.Millisecond)
		select {
		case <-operationContext.Done():
			timer.Stop()
			return FullCDPInteractionResult{}, operationContext.Err()
		case <-timer.C:
		}
	}
	return newFullCDPInteractionResult(finalURL, "click", selector), nil
}

func (runtime *FullCDPSession) TypeFullCDP(ctx context.Context,
	selector, value string,
) (FullCDPInteractionResult, error) {
	if runtime == nil || !runtime.authorization.DOMMetadataAuthorized ||
		!validFullCDPModelSelector(selector) || value == "" ||
		len([]byte(value)) > MaxFullCDPModelInputBytes || !utf8.ValidString(value) ||
		strings.ContainsRune(value, 0) || redact.String(value) != value {
		return FullCDPInteractionResult{}, ErrBrowserRuntimeBoundary
	}
	release, operationContext, cancel, err := runtime.beginOperation(ctx)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	defer release()
	defer cancel()
	before, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	provenance, err := runtime.authorizeFullCDPSelector(before, selector, true)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	nodeID, found, err := runtime.client.querySelector(operationContext, selector)
	if err != nil {
		return FullCDPInteractionResult{}, err
	}
	if !found {
		return FullCDPInteractionResult{}, errors.New("full CDP selector did not match")
	}
	element, err := runtime.client.describeFullCDPElement(operationContext, nodeID)
	if err != nil || validateFullCDPElement(provenance, element, true) != nil {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP type target is not an interactive snapshotted input"))
	}
	stable, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(stable) {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP document changed before input focus"))
	}
	if err := runtime.client.call(operationContext, runtime.client.sessionID,
		"DOM.focus", map[string]any{"nodeId": nodeID}, &struct{}{}); err != nil {
		return FullCDPInteractionResult{}, err
	}
	afterFocus, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(afterFocus) {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP document changed while the input was focused"))
	}
	focusedElement, err := runtime.client.describeFullCDPElement(operationContext, nodeID)
	if err != nil || focusedElement.BackendNodeID != element.BackendNodeID ||
		validateFullCDPElement(provenance, focusedElement, true) != nil {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP input target changed while it was focused"))
	}
	runtime.clearFullCDPSelectorSnapshot()
	if err := runtime.client.call(operationContext, runtime.client.sessionID,
		"Input.insertText", map[string]any{"text": value}, &struct{}{}); err != nil {
		return FullCDPInteractionResult{}, err
	}
	after, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(after) {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP document changed while text was inserted"))
	}
	afterNodeID, found, err := runtime.client.querySelector(operationContext, selector)
	if err != nil || !found {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP input target disappeared after text insertion"))
	}
	afterElement, err := runtime.client.describeFullCDPElement(operationContext, afterNodeID)
	if err != nil || afterElement.BackendNodeID != element.BackendNodeID ||
		validateFullCDPElement(provenance, afterElement, true) != nil {
		return FullCDPInteractionResult{}, errors.Join(err,
			errors.New("full CDP input target changed after text insertion"))
	}
	return newFullCDPInteractionResult(after.CanonicalURL, "type", selector), nil
}

func (runtime *FullCDPSession) ScreenshotFullCDP(ctx context.Context) (
	FullCDPScreenshotCapture, error,
) {
	if runtime == nil || !runtime.authorization.ScreenshotAuthorized {
		return FullCDPScreenshotCapture{}, ErrBrowserRuntimeBoundary
	}
	release, operationContext, cancel, err := runtime.beginOperation(ctx)
	if err != nil {
		return FullCDPScreenshotCapture{}, err
	}
	defer release()
	defer cancel()
	before, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil {
		return FullCDPScreenshotCapture{}, err
	}
	screenshot, err := runtime.client.captureScreenshot(operationContext,
		runtime.authorization.Fingerprint)
	if err != nil {
		return FullCDPScreenshotCapture{}, err
	}
	after, _, err := runtime.client.captureFullCDPDocument(operationContext, true)
	if err != nil || !before.sameExact(after) ||
		screenshot.CanonicalURL != before.CanonicalURL {
		runtime.clearFullCDPSelectorSnapshot()
		return FullCDPScreenshotCapture{}, errors.Join(err,
			errors.New("full CDP document changed while the screenshot was captured"))
	}
	result := FullCDPScreenshotMetadata{ProtocolVersion: FullCDPScreenshotProtocolVersion,
		CanonicalURL: screenshot.CanonicalURL, MediaType: screenshot.MediaType,
		Bytes: screenshot.Bytes, SHA256: screenshot.SHA256, UntrustedEvidence: true,
		CompletedAt: screenshot.CompletedAt}
	result.Fingerprint = browserRuntimeFingerprint(result)
	return FullCDPScreenshotCapture{Metadata: result,
		PNG: append([]byte(nil), screenshot.PNG...)}, nil
}

func (runtime *FullCDPManagedRuntime) BrowserNavigate(ctx context.Context,
	url string,
) (RestrictedNavigationResult, error) {
	if runtime == nil || runtime.session == nil {
		return RestrictedNavigationResult{}, ErrBrowserRuntimeBoundary
	}
	return runtime.session.NavigateFullCDP(ctx, url)
}

func (runtime *FullCDPManagedRuntime) BrowserSnapshot(ctx context.Context) (
	FullCDPPageSnapshot, error,
) {
	if runtime == nil || runtime.session == nil {
		return FullCDPPageSnapshot{}, ErrBrowserRuntimeBoundary
	}
	return runtime.session.SnapshotFullCDP(ctx)
}

func (runtime *FullCDPManagedRuntime) BrowserClick(ctx context.Context,
	selector string,
) (FullCDPInteractionResult, error) {
	if runtime == nil || runtime.session == nil {
		return FullCDPInteractionResult{}, ErrBrowserRuntimeBoundary
	}
	return runtime.session.ClickFullCDP(ctx, selector)
}

func (runtime *FullCDPManagedRuntime) BrowserType(ctx context.Context,
	selector, value string,
) (FullCDPInteractionResult, error) {
	if runtime == nil || runtime.session == nil {
		return FullCDPInteractionResult{}, ErrBrowserRuntimeBoundary
	}
	return runtime.session.TypeFullCDP(ctx, selector, value)
}

func (runtime *FullCDPManagedRuntime) BrowserScreenshot(ctx context.Context) (
	FullCDPScreenshotCapture, error,
) {
	if runtime == nil || runtime.session == nil {
		return FullCDPScreenshotCapture{}, ErrBrowserRuntimeBoundary
	}
	return runtime.session.ScreenshotFullCDP(ctx)
}

// CancelBrowserAction interrupts the active CDP transport immediately. It is
// used when the application observes a durable browser-permission change that
// the process-local execution authority cannot itself see.
func (runtime *FullCDPManagedRuntime) CancelBrowserAction() {
	if runtime != nil && runtime.session != nil {
		runtime.session.interruptBrowserActionTransport()
	}
}

func newFullCDPInteractionResult(canonicalURL, action,
	selector string,
) FullCDPInteractionResult {
	result := FullCDPInteractionResult{ProtocolVersion: FullCDPInteractionProtocolVersion,
		CanonicalURL: canonicalURL, Action: action, Selector: selector,
		CompletedAt: time.Now().UTC()}
	result.Fingerprint = browserRuntimeFingerprint(result)
	return result
}

func summarizeFullCDPDocument(document *html.Node) (string, string,
	[]FullCDPPageElement, bool,
) {
	if document == nil {
		return "", "", []FullCDPPageElement{}, false
	}
	title := ""
	var text strings.Builder
	elements := make([]FullCDPPageElement, 0, 32)
	truncated := false
	var walk func(*html.Node, bool)
	walk = func(node *html.Node, hidden bool) {
		if node == nil {
			return
		}
		if node.Type == html.ElementNode {
			tag := strings.ToLower(node.Data)
			hidden = hidden || tag == "script" || tag == "style" || tag == "noscript" ||
				hasHTMLAttribute(node, "hidden") || strings.EqualFold(htmlAttribute(node, "aria-hidden"), "true")
			if tag == "title" && title == "" {
				title = boundedFullCDPText(nodeText(node), MaxFullCDPPageElementTextRunes)
			}
			if !hidden && isFullCDPInteractiveTag(tag) &&
				len(elements) < MaxFullCDPPageSnapshotElements {
				selector := fullCDPSelector(node)
				if validFullCDPModelSelector(selector) {
					name := htmlAttribute(node, "aria-label")
					if name == "" {
						name = htmlAttribute(node, "title")
					}
					if name == "" {
						name = nodeText(node)
					}
					elements = append(elements, FullCDPPageElement{Selector: selector,
						Tag: tag, Role: boundedFullCDPText(htmlAttribute(node, "role"), 128),
						Name: boundedFullCDPText(name, MaxFullCDPPageElementTextRunes),
						Type: boundedFullCDPText(htmlAttribute(node, "type"), 128),
						Disabled: hasHTMLAttribute(node, "disabled") ||
							strings.EqualFold(htmlAttribute(node, "aria-disabled"), "true")})
				}
			} else if !hidden && isFullCDPInteractiveTag(tag) {
				truncated = true
			}
		}
		if node.Type == html.TextNode && !hidden {
			value := strings.Join(strings.Fields(node.Data), " ")
			if value != "" {
				if text.Len() > 0 {
					text.WriteByte(' ')
				}
				remaining := MaxFullCDPPageSnapshotTextBytes - text.Len()
				if remaining <= 0 {
					truncated = true
				} else if len([]byte(value)) > remaining {
					text.WriteString(trimUTF8Bytes(value, remaining))
					truncated = true
				} else {
					text.WriteString(value)
				}
			}
		}
		for child := node.FirstChild; child != nil; child = child.NextSibling {
			walk(child, hidden)
		}
	}
	walk(document, false)
	return boundedFullCDPText(title, MaxFullCDPPageElementTextRunes),
		boundedFullCDPText(text.String(), MaxFullCDPPageSnapshotTextBytes), elements, truncated
}

func validFullCDPModelSelector(value string) bool {
	if !validUIEvidenceSelector(value) {
		return false
	}
	if strings.HasPrefix(value, "#") {
		return fullCDPSimpleID.MatchString(strings.TrimPrefix(value, "#"))
	}
	parts := strings.Split(value, " > ")
	if len(parts) == 0 || len(parts) > 12 {
		return false
	}
	for _, part := range parts {
		if !fullCDPSelectorPart.MatchString(part) {
			return false
		}
	}
	last := parts[len(parts)-1]
	tag, _, _ := strings.Cut(last, ":")
	return isFullCDPInteractiveTag(tag)
}

func isFullCDPInteractiveTag(tag string) bool {
	switch tag {
	case "a", "button", "input", "select", "textarea", "summary":
		return true
	default:
		return false
	}
}

func fullCDPSelector(node *html.Node) string {
	if id := htmlAttribute(node, "id"); fullCDPSimpleID.MatchString(id) &&
		redact.String(id) == id {
		return "#" + id
	}
	parts := make([]string, 0, 8)
	for current := node; current != nil && current.Type != html.DocumentNode &&
		len(parts) < 12; current = current.Parent {
		if current.Type != html.ElementNode {
			continue
		}
		tag := strings.ToLower(current.Data)
		index := 1
		for sibling := current.PrevSibling; sibling != nil; sibling = sibling.PrevSibling {
			if sibling.Type == html.ElementNode && strings.EqualFold(sibling.Data, current.Data) {
				index++
			}
		}
		parts = append(parts, fmt.Sprintf("%s:nth-of-type(%d)", tag, index))
		if tag == "body" || tag == "html" {
			break
		}
	}
	for left, right := 0, len(parts)-1; left < right; left, right = left+1, right-1 {
		parts[left], parts[right] = parts[right], parts[left]
	}
	return strings.Join(parts, " > ")
}

func nodeText(node *html.Node) string {
	var builder strings.Builder
	var walk func(*html.Node)
	walk = func(current *html.Node) {
		if current == nil {
			return
		}
		if current.Type == html.ElementNode {
			switch strings.ToLower(current.Data) {
			case "script", "style", "noscript":
				return
			}
		}
		if current.Type == html.TextNode {
			if builder.Len() > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteString(current.Data)
		}
		for child := current.FirstChild; child != nil; child = child.NextSibling {
			walk(child)
		}
	}
	walk(node)
	return strings.Join(strings.Fields(builder.String()), " ")
}

func htmlAttribute(node *html.Node, name string) string {
	if node == nil {
		return ""
	}
	for _, attribute := range node.Attr {
		if strings.EqualFold(attribute.Key, name) {
			return strings.TrimSpace(attribute.Val)
		}
	}
	return ""
}

func hasHTMLAttribute(node *html.Node, name string) bool {
	if node == nil {
		return false
	}
	for _, attribute := range node.Attr {
		if strings.EqualFold(attribute.Key, name) {
			return true
		}
	}
	return false
}

func boundedFullCDPText(value string, limit int) string {
	value = strings.TrimSpace(outputsafe.Sanitize([]byte(value)))
	value = redact.String(strings.Join(strings.Fields(value), " "))
	if limit <= 0 {
		return ""
	}
	if utf8.RuneCountInString(value) > limit && limit < MaxFullCDPPageSnapshotTextBytes {
		runes := []rune(value)
		value = string(runes[:limit])
	}
	if len([]byte(value)) > limit && limit >= MaxFullCDPPageSnapshotTextBytes {
		value = trimUTF8Bytes(value, limit)
	}
	return value
}

func trimUTF8Bytes(value string, limit int) string {
	if limit <= 0 {
		return ""
	}
	for len([]byte(value)) > limit {
		_, size := utf8.DecodeLastRuneInString(value)
		value = value[:len(value)-size]
	}
	return value
}
