//go:build clean_install_baseline_generate

package store

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateCleanInstallBaselineArtifacts is available only to the generator
// build. It deliberately constructs the source database through every legacy
// migration instead of calling Open, so generation can never validate itself.
func GenerateCleanInstallBaselineArtifacts(ctx context.Context, sqlPath, metadataPath string) error {
	directory, err := os.MkdirTemp("", "traverse-board-clean-install-baseline-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(directory)
	databasePath := filepath.Join(directory, "legacy.db")
	db, err := sql.Open("sqlite3", sqliteDSN(databasePath))
	if err != nil {
		return err
	}
	defer db.Close()
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	if _, err := db.ExecContext(ctx, `PRAGMA foreign_keys = ON;`); err != nil {
		return err
	}
	state := &SQLiteStore{db: db, home: directory}
	plan := migrationPlan()
	if err := state.applyMigrations(ctx, plan); err != nil {
		return fmt.Errorf("build legacy baseline source: %w", err)
	}
	if err := requireEmptyApplicationTables(ctx, db); err != nil {
		return err
	}

	statements, err := readBaselineSchemaStatements(ctx, db)
	if err != nil {
		return err
	}
	script := strings.Join(statements, ";"+cleanInstallBaselineStatementSeparator) + ";\n"
	schemaDigest, err := sqliteSchemaDigest(ctx, db)
	if err != nil {
		return err
	}
	sqlDigest := fmt.Sprintf("%x", sha256Sum(script))
	metadata := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package store

const (
	cleanInstallBaselineSchemaVersion = %d
	cleanInstallBaselineSQLSHA256 = %q
	cleanInstallBaselineSchemaSHA256 = %q
	cleanInstallBaselineMigrationPlanSHA256 = %q
)
`, LatestSchemaVersion, sqlDigest, schemaDigest, migrationPlanDigest(plan))
	formatted, err := format.Source([]byte(metadata))
	if err != nil {
		return fmt.Errorf("format clean-install metadata: %w", err)
	}
	if err := os.WriteFile(sqlPath, []byte(script), 0o600); err != nil {
		return fmt.Errorf("write clean-install SQL: %w", err)
	}
	if err := os.WriteFile(metadataPath, formatted, 0o600); err != nil {
		return fmt.Errorf("write clean-install metadata: %w", err)
	}
	return nil
}

func readBaselineSchemaStatements(ctx context.Context, db *sql.DB) ([]string, error) {
	rows, err := db.QueryContext(ctx, `SELECT type, name, sql FROM main.sqlite_schema
		WHERE name NOT LIKE 'sqlite\_%' ESCAPE '\' AND sql IS NOT NULL`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	type schemaObject struct {
		kind, name, statement string
	}
	objects := make([]schemaObject, 0)
	for rows.Next() {
		var object schemaObject
		if err := rows.Scan(&object.kind, &object.name, &object.statement); err != nil {
			return nil, err
		}
		objects = append(objects, object)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	order := map[string]int{"table": 0, "view": 1, "index": 2, "trigger": 3}
	sort.Slice(objects, func(i, j int) bool {
		left, right := order[objects[i].kind], order[objects[j].kind]
		if left != right {
			return left < right
		}
		return objects[i].name < objects[j].name
	})
	statements := make([]string, 0, len(objects))
	for _, object := range objects {
		statement := strings.TrimSpace(object.statement)
		statement = strings.TrimSuffix(statement, ";")
		if statement == "" {
			return nil, fmt.Errorf("empty SQL for %s %q", object.kind, object.name)
		}
		if strings.Contains(statement, cleanInstallBaselineStatementSeparator) {
			return nil, fmt.Errorf("reserved baseline separator in %s %q", object.kind, object.name)
		}
		statements = append(statements, statement)
	}
	return statements, nil
}

func requireEmptyApplicationTables(ctx context.Context, db *sql.DB) error {
	rows, err := db.QueryContext(ctx, `SELECT name FROM main.sqlite_schema
		WHERE type = 'table' AND name NOT LIKE 'sqlite\_%' ESCAPE '\'
			AND name <> 'schema_migrations' ORDER BY name`)
	if err != nil {
		return err
	}
	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			_ = rows.Close()
			return err
		}
		tables = append(tables, name)
	}
	if err := rows.Close(); err != nil {
		return err
	}
	for _, table := range tables {
		var count int
		quoted := `"` + strings.ReplaceAll(table, `"`, `""`) + `"`
		if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM `+quoted).Scan(&count); err != nil {
			return err
		}
		if count != 0 {
			return fmt.Errorf("legacy clean install unexpectedly seeded %s with %d rows", table, count)
		}
	}
	return nil
}

func sha256Sum(value string) [32]byte {
	return sha256.Sum256([]byte(value))
}
