// Code generated by go generate; DO NOT EDIT.

package store

const (
	cleanInstallBaselineSchemaVersion       = 173
	cleanInstallBaselineSQLSHA256           = "80cf52c4c8b54a931eee8f8e137401f72f0320a81903bd020fe824f1bdeb9c88"
	cleanInstallBaselineSchemaSHA256        = "ef82c48876cc6f013440979065819d853d20997782b01ec5b801001e11b74733"
	cleanInstallBaselineMigrationPlanSHA256 = "d969ce05ddefbc2173839d80b9c70c8e4783a7ed786d6be6c6fba149b71a493d"
)
