// Code generated by go generate; DO NOT EDIT.

package store

const (
	cleanInstallBaselineSchemaVersion       = 177
	cleanInstallBaselineSQLSHA256           = "831a348ced306da55f19a8d6de5eaf01860aa8ca5904549f2f6181afc3c6009e"
	cleanInstallBaselineSchemaSHA256        = "f1e5bbc0c7c22a5a718e7f86e9104cf3fe13f20521767f0de9bae8f5881520c0"
	cleanInstallBaselineMigrationPlanSHA256 = "a4e0dbc3f639d976ba089f64d19addb6f6eecd1005d864b921082ae8afeafd43"
)
