// Code generated by go generate; DO NOT EDIT.

package store

const (
	cleanInstallBaselineSchemaVersion       = 178
	cleanInstallBaselineSQLSHA256           = "a4fd48a7bd35271dd48dff7523412b7a6a918bda0126de197844b6c1ec2dcfef"
	cleanInstallBaselineSchemaSHA256        = "135b648479220aecd46ba8d9bb9ec3e2a7d6820c38dd922e728b3a3830d8a4f1"
	cleanInstallBaselineMigrationPlanSHA256 = "dcd2aad735d53b99cadc84fd9353891f58f1f302b5c6e35fffd2ba8d47b09396"
)
