package store

var childTaskStatements = []string{
	`CREATE TABLE child_task_proposals (
		id TEXT PRIMARY KEY,
		run_id TEXT NOT NULL,
		root_agent_id TEXT NOT NULL,
		session_id TEXT NOT NULL,
		workspace_id TEXT NOT NULL,
		status TEXT NOT NULL,
		spec_json TEXT NOT NULL,
		surface TEXT NOT NULL,
		fanout_tier TEXT NOT NULL,
		dedup_fingerprint TEXT NOT NULL UNIQUE,
		requested_by TEXT NOT NULL,
		version INTEGER NOT NULL,
		created_at TEXT NOT NULL,
		reviewed_at TEXT,
		reviewer TEXT NOT NULL DEFAULT '',
		FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE RESTRICT,
		CHECK(status IN ('proposed', 'approved', 'denied')),
		CHECK(surface IN ('core', 'readonly_fanout')),
		CHECK(fanout_tier IN ('', '1', '2', '4', '6')),
		CHECK((status = 'proposed') = (reviewed_at IS NULL)),
		CHECK((status <> 'proposed') = (reviewer <> '')),
		CHECK(id = trim(id) AND length(id) BETWEEN 1 AND 256 AND instr(id, char(0)) = 0),
		CHECK(run_id = trim(run_id) AND length(run_id) BETWEEN 1 AND 256 AND instr(run_id, char(0)) = 0),
		CHECK(root_agent_id = trim(root_agent_id) AND length(root_agent_id) BETWEEN 1 AND 256),
		CHECK(length(dedup_fingerprint) = 64 AND dedup_fingerprint = lower(dedup_fingerprint)),
		CHECK(json_valid(spec_json) AND length(spec_json) BETWEEN 1 AND 32768),
		CHECK(version >= 1),
		CHECK(julianday(created_at) IS NOT NULL)
	);`,
	`CREATE TABLE child_task_proposal_operations (
		operation_key_digest TEXT PRIMARY KEY,
		request_fingerprint TEXT NOT NULL,
		proposal_id TEXT NOT NULL UNIQUE,
		created_at TEXT NOT NULL,
		FOREIGN KEY(proposal_id) REFERENCES child_task_proposals(id) ON DELETE RESTRICT,
		CHECK(length(operation_key_digest) = 64 AND length(request_fingerprint) = 64),
		CHECK(julianday(created_at) IS NOT NULL)
	) WITHOUT ROWID;`,
	`CREATE TABLE child_task_review_operations (
		operation_key_digest TEXT PRIMARY KEY,
		request_fingerprint TEXT NOT NULL,
		proposal_id TEXT NOT NULL UNIQUE,
		created_at TEXT NOT NULL,
		UNIQUE(proposal_id),
		FOREIGN KEY(proposal_id) REFERENCES child_task_proposals(id) ON DELETE RESTRICT,
		CHECK(length(operation_key_digest) = 64 AND length(request_fingerprint) = 64),
		CHECK(julianday(created_at) IS NOT NULL)
	) WITHOUT ROWID;`,
	`CREATE TABLE child_task_assignments (
		proposal_id TEXT NOT NULL,
		ordinal INTEGER NOT NULL,
		surface TEXT NOT NULL,
		fanout_tier TEXT NOT NULL,
		status TEXT NOT NULL,
		dependency_ordinals_json TEXT NOT NULL,
		turn_limit INTEGER NOT NULL,
		token_limit INTEGER NOT NULL,
		timeout_millis INTEGER NOT NULL,
		admitted_agent_id TEXT NOT NULL DEFAULT '',
		fanout_plan_id TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY(proposal_id, ordinal),
		FOREIGN KEY(proposal_id) REFERENCES child_task_proposals(id) ON DELETE RESTRICT,
		CHECK(surface IN ('core', 'readonly_fanout')),
		CHECK(fanout_tier IN ('', '1', '2', '4', '6')),
		CHECK(status IN ('proposed', 'admitted')),
		CHECK(ordinal BETWEEN 1 AND 6),
		CHECK(turn_limit BETWEEN 1 AND 1000),
		CHECK(token_limit BETWEEN 1 AND 9007199254740991),
		CHECK(timeout_millis BETWEEN 1 AND 1800000),
		CHECK(json_valid(dependency_ordinals_json)),
		CHECK(julianday(created_at) IS NOT NULL AND julianday(updated_at) IS NOT NULL)
	) WITHOUT ROWID;`,
}

