package store

var onceCommandProposalStatements = []string{
	`CREATE TABLE once_command_proposal_operations (
		operation_key_digest TEXT PRIMARY KEY,
		request_fingerprint TEXT NOT NULL,
		proposal_id TEXT NOT NULL UNIQUE,
		FOREIGN KEY(proposal_id) REFERENCES once_command_proposals(id) ON DELETE RESTRICT,
		CHECK(length(operation_key_digest) = 64 AND length(request_fingerprint) = 64)
	) WITHOUT ROWID;`,
	`CREATE TABLE once_command_proposals (
		id TEXT PRIMARY KEY,
		protocol_version TEXT NOT NULL,
		operation_key_digest TEXT NOT NULL UNIQUE,
		request_fingerprint TEXT NOT NULL UNIQUE,
		run_id TEXT NOT NULL,
		root_agent_id TEXT NOT NULL,
		session_id TEXT NOT NULL,
		workspace_id TEXT NOT NULL,
		executable_path TEXT NOT NULL,
		argv_json TEXT NOT NULL,
		working_directory TEXT NOT NULL,
		environment_keys_json TEXT NOT NULL,
		environment_sha256 TEXT NOT NULL,
		timeout_milliseconds INTEGER NOT NULL,
		purpose TEXT NOT NULL,
		spec_fingerprint TEXT NOT NULL,
		status TEXT NOT NULL,
		reviewer TEXT NOT NULL DEFAULT '',
		review_reason TEXT NOT NULL DEFAULT '',
		reviewed_at TEXT,
		approval_fingerprint TEXT NOT NULL DEFAULT '',
		execution_request_fingerprint TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE RESTRICT,
		CHECK(protocol_version = 'once_command.v1'),
		CHECK(status IN ('proposed', 'approved', 'denied', 'executed')),
		CHECK((status = 'proposed') = (reviewed_at IS NULL)),
		CHECK((status IN ('approved', 'executed')) = (approval_fingerprint <> '')),
		CHECK((status = 'denied') = (approval_fingerprint = '' AND review_reason <> '')),
		CHECK(length(id) BETWEEN 1 AND 256 AND instr(id, char(0)) = 0),
		CHECK(length(operation_key_digest) = 64 AND length(request_fingerprint) = 64),
		CHECK(length(spec_fingerprint) = 64),
		CHECK(json_valid(argv_json) AND json_valid(environment_keys_json)),
		CHECK(length(environment_sha256) = 64),
		CHECK(timeout_milliseconds BETWEEN 1 AND 600000),
		CHECK(julianday(created_at) IS NOT NULL)
	);`,
}
